# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import getpass
import json

# Import API key
#from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities_df = pd.read_csv("../WeatherPy/cities.csv")
cities_df.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,ostrovnoy,2,RU,1558378754,72,68.05,39.51,37.50,7.16
1,1,mahebourg,75,MU,1558378503,74,-20.41,57.70,78.80,11.41
2,2,qaanaaq,25,GL,1558378755,73,77.48,-69.36,22.20,2.37
3,3,zhuhai,0,CN,1558378755,39,40.71,112.04,44.60,4.47
4,4,cape town,20,ZA,1558378755,76,-33.93,18.42,55.99,8.05

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=getpass.getpass())

········

In [4]:
#Heatmap of humidity
locations = cities_df[["Lat", "Lng"]]
humidity = cities_df["Humidity"]
max_temp = cities_df["Max Temp"]
wind_speed = cities_df["Wind Speed"]
cloudiness = cities_df["Cloudiness"]
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating = False, max_intensity = 300, point_radius=5)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
narrow_cities_df = cities_df.loc[(cities_df["Max Temp"]<86) & (cities_df["Max Temp"]>32)&(cities_df["Wind Speed"] < 10)\
                                 & (cities_df["Cloudiness"]==0).dropna()]
narrow_cities_df.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
3,3,zhuhai,0,CN,1558378755,39,40.71,112.04,44.60,4.47
7,7,opuwo,0,NaN,1558378523,23,-18.06,13.84,72.06,5.44
11,11,castro,0,CL,1558378756,70,-42.48,-73.76,48.20,9.17
30,30,gobabis,0,NaN,1558378567,24,-22.45,18.97,68.00,2.24
31,31,qingdao,0,CN,1558378760,54,36.09,120.35,59.00,2.24

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = narrow_cities_df[['City', 'Country', 'Lat', 'Lng']]
hotel_df['Hotel Name'] = ''
hotel_df.head()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       City Country    Lat     Lng Hotel Name
3    zhuhai      CN  40.71  112.04
7     opuwo     NaN -18.06   13.84
11   castro      CL -42.48  -73.76
30  gobabis     NaN -22.45   18.97
31  qingdao      CN  36.09  120.35

In [7]:
params = {
    "types": "hotel",
    "keyword" : "hotels",
    "radius":5000,
    "key": getpass.getpass()
}

········

In [12]:
for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    hotel = requests.get(base_url, params=params)
    hotel = hotel.json()
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
hotel_df

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

,City,Country,Lat,Lng,Hotel Name
3,zhuhai,CN,40.71,112.04,
7,opuwo,NaN,-18.06,13.84,Opuwo Country Lodge
11,castro,CL,-42.48,-73.76,Apart Hotel y Cabañas Nomades
30,gobabis,NaN,-22.45,18.97,Goba Lodge
31,qingdao,CN,36.09,120.35,The Westin Qingdao
37,varhaug,NO,58.61,5.65,Huset ved havet
57,kolyvan,RU,55.31,82.74,
70,ponta do sol,BR,-20.63,-46.00,Escarpas do Lago
84,emerald,AU,-23.53,148.16,Emerald Executive Apartments
88,cidreira,BR,-30.17,-50.22,Pond Country Club
112,bredasdorp,ZA,-34.53,20.04,A Piece Of Life
125,arraial do cabo,BR,-22.97,-42.02,Hotel da Canoa
138,morondava,MG,-20.30,44.28,Palissandre Cote Ouest resort & SPA
139,vaini,IN,15.34,74.49,Dandeli Mist Jungle Stay
141,sanchazi,CN,30.43,103.62,
168,straumen,NO,63.87,11.30,SAGA - Center of Photography
176,nador,MA,35.17,-2.93,Hôtel Mercure Rif Nador
192,port hedland,AU,-20.31,118.58,ibis Styles Port Hedland
214,mount isa,AU,-20.73,139.49,Abacus Motel
220,ust-tsilma,RU,65.44,52.15,
248,ancud,CL,-41.87,-73.83,13 Lunas Hostel
252,kajaani,FI,64.22,27.73,Hotel Kajaani
259,hami,CN,42.84,93.51,Hami Hotel
263,markova,RU,52.21,104.21,
271,coihaique,CL,-45.58,-72.07,Hostal Salamandras
297,mogok,MM,22.92,96.51,King Bridge
298,mikkeli,FI,61.69,27.27,Gasthaus Mikkeli
299,jiuquan,CN,39.73,98.49,Jiuquan Hotel
314,baruun-urt,MN,46.68,113.28,Эрхэт зочид буудал
316,gunjur,GM,13.18,-16.76,Footsteps Eco Lodge
340,la libertad,PE,-16.38,-71.56,Resort Suite Confort
346,chiredzi,ZW,-21.05,31.67,The Nesbitt Arms
359,sorland,NO,67.67,12.69,Lofoten Værøy Brygge
362,datong,CN,40.09,113.30,Datong Weidu International Hotel
371,carballo,ES,43.21,-8.69,Pazo do Souto
376,qinhuangdao,CN,39.94,119.59,International Hotel Qinhuangdao
427,hastings,NZ,-39.64,176.84,Apple Motor Inn
433,svodin,SK,47.91,18.50,
438,waipawa,NZ,-39.94,176.59,
444,birjand,IR,32.86,59.22,Mountain Hotel
446,henties bay,NaN,-22.12,14.28,Huis Klipdrift
477,bundaberg,AU,-24.87,152.35,Best Western Bundaberg City Motor Inn
500,mandalgovi,MN,45.76,106.27,Mandal Hotel
508,noumea,NC,-22.28,166.46,Hilton Noumea La Promenade Residences
518,bonito,BR,-21.13,-56.49,Zagaia Eco Resort
527,tomatlan,MX,19.93,-105.25,Hotel Misión San Miguel
533,hakkari,FI,61.34,23.75,Lempäälä
538,la seyne-sur-mer,FR,43.10,5.88,ibis budget Toulon Centre
543,yabrud,SY,33.97,36.66,
545,veraval,FR,49.65,0.71,B&B HOTEL

In [17]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [18]:
# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
fig

# Display Map

Figure(layout=FigureLayout(height='420px'))